services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoP\GuzzleHTTP\Services\GuzzleServiceInterface:
        class: \PoP\GuzzleHTTP\Services\GuzzleService